services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      APP_DEBUG: True
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_DATABASE: boardgame_web
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: boardgame_web
      MYSQL_USER: boardgame_user
      MYSQL_PASSWORD: pass
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
